import turtle
snow = turtle.Turtle()
finestra = turtle.Screen()
snow.speed(100)
f = open("scriviFile.txt", 'w')

for _ in range(4):
    snow.forward(100)
    f.write("forward:" + str(100) + "\n")
    snow.left(45)
    f.write("left:" + str(45) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(-135)
    f.write("left:" + str(-135) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(70)
    f.write("forward:" + str(70) + "\n")
    snow.left(135)
    f.write("left:" + str(135) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.right(90)
    f.write("right:" + str(90) + "\n")
    for _ in range(3):
        snow.forward(15)
        f.write("forward:" + str(15) + "\n")
        snow.left(90)
        f.write("left:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.right(90)
    f.write("right:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(15) 
    f.write("forward:" + str(15) + "\n")
    snow.right(45)
    f.write("right:" + str(45) + "\n")
    snow.forward(50)
    f.write("forward:" + str(50) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")

for _ in range(4):
    snow.right(45)
    f.write("right:" + str(45) + "\n")
    snow.forward(100)
    f.write("forward:" + str(100) + "\n")
    snow.left(45)
    f.write("left:" + str(45) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(-135)
    f.write("left:" + str(-135) + "\n")
    snow.forward(20)
    f.write("forward:" + str(20) + "\n")
    snow.left(180)
    f.write("left:" + str(180) + "\n")
    snow.forward(70)
    f.write("forward:" + str(70) + "\n")
    snow.right(135)
    f.write("right:" + str(135) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(90)
    f.write("left:" + str(90) + "\n")
    snow.forward(30)
    f.write("forward:" + str(30) + "\n")
    snow.right(90)
    f.write("right:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.right(90)
    f.write("right:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.right(90)
    f.write("right:" + str(90) + "\n")
    snow.forward(15)
    f.write("forward:" + str(15) + "\n")
    snow.left(135)
    f.write("left:" + str(135) + "\n")
    snow.forward(50)
    f.write("forward:" + str(50) + "\n")
    snow.right(45)
    f.write("right:" + str(45) + "\n")
finestra.exitonclick()
f.close()